# Site settings
title: Mislav Javor
email: mislav.javor@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  A blog where I talk about the things I know about. Mostly it's
  software development and audio engineering, but be warned - 
  I am a stranger to no topic.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "mislavjavor.github.io" # the base hostname & protocol for your site
twitter_username: mislavcodes
github_username:  mislavjavor

# Build settings
markdown: kramdown

kramdown:
 input: GFM
 syntax_highlighter: pygments

highlighter: pygments